### ISSUE TITLE
Code generation plugin fails when generating schema for older Caliban servers

### ISSUE THREAD

**Issue by andriygm** [ghostdogpr/caliban#1726]
Code generation plugin gets a `Cannot query field 'isRepeatable' on type '__Directive'` response when trying to generate schema for an older server. Tested with Caliban client 2.2.1 and server 1.2.1. Issue does not seem to be present on clients earlier than 2.1.0.

**Comment by ghostdogpr** [comment]
One option I see is to add a boolean option to the codegen (and the introspect method) to include or not this new field `isRepeatable` so that it would still work with old servers that don't support it.

**Comment by ghostdogpr** [comment]
@andriygm i just merged my PR. Would you be able to test with the snapshot that's about to be created and confirm it works well?

**Comment by andriygm** [comment]
Issue still seems to be present on [2.2.1+9-6f9efdbe-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/github/ghostdogpr/caliban_2.12/2.2.1+9-6f9efdbe-SNAPSHOT/)

**Comment by ghostdogpr** [comment]
@andriygm ah, I did not mention it but you need to add a new option `supportIsRepeatable` set to false.

**Comment by andriygm** [comment]
Looks like [2.2.1+12-eebff90d-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/github/ghostdogpr/caliban_2.12/2.2.1+12-eebff90d-SNAPSHOT/) fixes this. Had to test using Scala 3.3.1-RC1-bin-20230525-2e19304-NIGHTLY due to TASTy format incompatibility.

**Comment by ghostdogpr** [comment]
Ah didn't it work with just 3.3.0? We already upgraded even though the release was not announced yet 😄

**Comment by andriygm** [comment]
I couldn't get it working with 3.3.0-RC6, but maybe I'm missing something.

**Comment by ghostdogpr** [comment]
How about just 3.3.0?

**Comment by andriygm** [comment]
3.3.0 does seem to work! Didn't even notice that release was tagged.

**Comment by ghostdogpr** [comment]
Yeah I will wait until it is officially announced before releasing the next version of caliban. 😄  Thanks for confirming the fix!
